### ISSUE TITLE
ImportError: cannot import name 'PointTensor' from 'torchsparse'

### ISSUE THREAD

**Issue by binaryannamolly** [FengZicai/Cluster3Dseg#4]
I am having this error,

ImportError: cannot import name 'PointTensor' from 'torchsparse' (.../lib/python3.10/site-packages/torchsparse/__init__.py)

Any idea show to resolve?

My environment,

- GCC: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- NVCC: Build cuda_11.8.r11.8/compiler.31833905_0
- PyTorch: 2.0.1
- PyTorch CUDA: cu118
- Python 3.10
- PyCharm 2023.2.3 (Professional Edition)

**Comment by FengZicai** [comment]
Torchsparse has been upgraded to TorchSparse++. 

Please install using the following command:

```
pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.4.0
```

If you have any other comments, please email: [feng.tuo@student.uts.edu.au](mailto:feng.tuo@student.uts.edu.au).

**Comment by binaryannamolly** [comment]
Thanks!! That worked.
